# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.10
#
# <auto-generated>
#
# Generated from file `PalindromeChecker.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Objects
_M_Objects = Ice.openModule('Objects')
__name__ = 'Objects'

_M_Objects._t_PalindromeChecker = IcePy.defineValue('::Objects::PalindromeChecker', Ice.Value, -1, (), False, True, None, ())

if 'PalindromeCheckerPrx' not in _M_Objects.__dict__:
    _M_Objects.PalindromeCheckerPrx = Ice.createTempClass()
    class PalindromeCheckerPrx(Ice.ObjectPrx):

        def isPalindrome(self, number, context=None):
            return _M_Objects.PalindromeChecker._op_isPalindrome.invoke(self, ((number, ), context))

        def isPalindromeAsync(self, number, context=None):
            return _M_Objects.PalindromeChecker._op_isPalindrome.invokeAsync(self, ((number, ), context))

        def begin_isPalindrome(self, number, _response=None, _ex=None, _sent=None, context=None):
            return _M_Objects.PalindromeChecker._op_isPalindrome.begin(self, ((number, ), _response, _ex, _sent, context))

        def end_isPalindrome(self, _r):
            return _M_Objects.PalindromeChecker._op_isPalindrome.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Objects.PalindromeCheckerPrx.ice_checkedCast(proxy, '::Objects::PalindromeChecker', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Objects.PalindromeCheckerPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Objects::PalindromeChecker'
    _M_Objects._t_PalindromeCheckerPrx = IcePy.defineProxy('::Objects::PalindromeChecker', PalindromeCheckerPrx)

    _M_Objects.PalindromeCheckerPrx = PalindromeCheckerPrx
    del PalindromeCheckerPrx

    _M_Objects.PalindromeChecker = Ice.createTempClass()
    class PalindromeChecker(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::Objects::PalindromeChecker')

        def ice_id(self, current=None):
            return '::Objects::PalindromeChecker'

        @staticmethod
        def ice_staticId():
            return '::Objects::PalindromeChecker'

        def isPalindrome(self, number, current=None):
            raise NotImplementedError("servant method 'isPalindrome' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Objects._t_PalindromeCheckerDisp)

        __repr__ = __str__

    _M_Objects._t_PalindromeCheckerDisp = IcePy.defineClass('::Objects::PalindromeChecker', PalindromeChecker, (), None, ())
    PalindromeChecker._ice_type = _M_Objects._t_PalindromeCheckerDisp

    PalindromeChecker._op_isPalindrome = IcePy.Operation('isPalindrome', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_long, False, 0),), (), ((), IcePy._t_bool, False, 0), ())

    _M_Objects.PalindromeChecker = PalindromeChecker
    del PalindromeChecker

# End of module Objects
